DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    ROLE VARCHAR(10) NOT NULL,
    IS_ACTUAL BOOLEAN NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);