DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(150) NOT NULL,
    ROLE VARCHAR(10) NOT NULL,
    IS_ACTUAL BOOLEAN NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT
(
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    PICTURE VARCHAR(250) NOT NULL,
    SHORT_DESCRIPTION VARCHAR(50) NOT NULL UNIQUE,
    DETAIL_DESCRIPTION VARCHAR(100) NOT NULL,
    PRICE DOUBLE NOT NULL,
    CREATION_DATE DATETIME NOT NULL,
    UPDATE_DATE DATETIME NOT NULL,
    CHANGED_BY INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

DROP TABLE IF EXISTS CART_RECORDS;
CREATE TABLE CART_RECORDS
(
    CUSTOMER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE
);